---
dist: focal
sudo: required
language: python

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python3-pip -qq

  # Allow running tasks as unprivileged users with travis CI
  # Reference: https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
  - sudo apt-get install acl -qq

  # Install systemd required for the service file
  - sudo apt-get install systemd -qq

install:
  # Install Ansible
  - pip install ansible
  - pip install ansible-lint

script:
  # Basic role syntax check
  - ansible-playbook tests/role.yml --syntax-check
  - ansible-lint tests/role.yml

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i "localhost," tests/role.yml --connection="local" --become

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i "localhost," tests/role.yml --connection=local --become
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
